
NAME = so_long
CC = gcc

LIBFT = ./libft/libft.a
LIBFT_DIR = ./libft

MINILIBX = minilibx-linux

CFLAGS = -Wasll -Wextra -Werror -lm -I include -I $(MINILIBX)


SRC = main.c
OBJ = $(SRC:.c=.o)

RM = rm -f
CP = cp
AR = ar rcs

